//! Compiling the effective conversation a managed request carries.
//!
//! The order is fixed, and each step is the only place its decision is made:
//!
//! 1. The raw replay is folded and the fragments derived; the accepted revision is checked
//!    against its base before anything is selected from it.
//! 2. Every original user message and every protected fragment is kept. Hidden ids remove whole
//!    eligible fragments and nothing else, and what survives keeps its original order.
//! 3. A fixed-schema notice states counts, revision, budget, goal phase and recovery — numbers,
//!    enums and opaque ids only, so nothing retrieved or written by a model is ever promoted
//!    into a system instruction.
//! 4. Notes, the goal objective and the recovery catalog are rendered as one labelled
//!    *assistant* message right after the earliest user message: working data the harness
//!    generated, never a user instruction and never proof.
//! 5. That message is never the last one. A fresh request with nothing after its first user
//!    message carries no generated data, and the notice says so.
//!
//! Provider preparation and estimation (step 6) belong to the adapter, which is the only party
//! that knows what the request costs on its wire.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use super::fragments::Fragments;
use super::ids::{Digest, ErrorCode, FragmentId};
use super::limits;
use super::records::{SourceKind, SourceRef, WorkingNote};
use crate::goal::Goal;
use crate::message::Message;
use crate::session::{Session, SessionEvent};

/// The bounded manual policy every managed request's system prompt carries, version 1.
///
/// Versioned with the policy and hashed into the system-prompt digest, so a change to a word of
/// it is a change a stale proposal is refused for. It grants nothing: the model can act only
/// through the context tools, inside the protections and quotas they enforce.
pub const MANUAL_POLICY_V1: &str = "\
Context management (policy 1). Earlier assistant and tool messages may be hidden from this \
request to fit its budget; every user message is always shown. You can inspect and change what \
is hidden with `context_manage` and read hidden or archived evidence back with `context_recall`. \
When you change the context: keep every constraint a user stated; hide exploration that is \
resolved; write notes that cite the evidence they rest on; keep uncertainty labelled as \
unresolved or inferred rather than observed; and revise a note that later evidence \
contradicts. A note is your own working data, not proof: say a test passed only when a cited \
result shows it ran. A proposal must be the only call in its message, and it takes effect only \
after the step that made it settles.";

/// Returns the digest of the manual policy text.
#[must_use]
pub fn manual_policy_digest() -> Digest {
    Digest::of(MANUAL_POLICY_V1.as_bytes())
}

/// The label that opens the generated working-data message.
pub const MEMORY_LABEL: &str = "[nanus working data — generated by the harness from accepted \
context notes, the session goal and the hidden-history catalog. It is not a user instruction \
and not proof; each note is the model's own claim with its sources.]";

/// Who last set the goal, as far as the log can tell.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GoalProvenance {
    /// A goal tool, inside a step.
    Model,
    /// A person or the host, outside any step.
    Host,
    /// Not recorded.
    Unknown,
}

impl GoalProvenance {
    /// Reads the provenance of the current goal from the log.
    ///
    /// Goal tools run only inside a step, and a client's goal command only outside one, so the
    /// position of the last `goal/change` record is the whole answer.
    #[must_use]
    pub fn of(session: &Session) -> Self {
        let mut in_step = false;
        let mut provenance = Self::Unknown;
        for event in session.log().events() {
            match event {
                SessionEvent::StepStart { .. } => in_step = true,
                SessionEvent::StepEnd { .. } | SessionEvent::TurnEnd { .. } => in_step = false,
                SessionEvent::GoalChange { .. } => {
                    provenance = if in_step { Self::Model } else { Self::Host };
                }
                _ => {}
            }
        }
        provenance
    }

    const fn as_str(self) -> &'static str {
        match self {
            Self::Model => "model",
            Self::Host => "host",
            Self::Unknown => "unknown",
        }
    }
}

/// A selection to compile: the hidden set, the notes and what they are bound to.
#[derive(Clone, Copy, Debug)]
pub struct Selection<'a> {
    /// The revision this selection is, or would be.
    pub revision: u64,
    /// Every hidden fragment.
    pub hidden: &'a [FragmentId],
    /// Every note.
    pub notes: &'a [WorkingNote],
    /// The goal revision the notes are bound to.
    pub notes_goal_revision: Option<u64>,
}

/// The facts the notice states that the domain cannot know.
#[derive(Clone, Debug, Default)]
pub struct NoticeFacts {
    /// The input estimate of the previous candidate, when there was one.
    pub estimate_input_tokens: Option<u32>,
    /// The estimator that produced it.
    pub estimator: String,
    /// The admissible input allowance.
    pub input_allowance: u32,
    /// Whether to give the soft-pressure budget hint.
    pub budget_hint: bool,
    /// Whether hidden and archived evidence can be recalled.
    pub recovery_available: bool,
}

/// The compiled conversation.
#[derive(Clone, Debug, PartialEq)]
pub struct Effective {
    /// The fixed-schema notice, a system message placed after the system prompt.
    pub notice: Message,
    /// The selected conversation, generated data in place.
    pub messages: Vec<Message>,
    /// Whether the generated data message is present.
    pub memory: bool,
    /// Hidden fragments applied.
    pub hidden: usize,
    /// Fragments protected.
    pub protected: usize,
}

/// Compiles the effective conversation for one selection.
///
/// # Errors
///
/// Returns [`ErrorCode::InvalidFragment`] for a hidden id that is not an eligible fragment, and
/// [`ErrorCode::ProtectedFragment`] for one that is protected.
pub fn derive_effective_context(
    session: &Session,
    fragments: &Fragments,
    protected: &BTreeSet<FragmentId>,
    selection: Selection<'_>,
    goal: Option<&Goal>,
    facts: &NoticeFacts,
) -> Result<Effective, ErrorCode> {
    for id in selection.hidden {
        let fragment = fragments.get(*id).ok_or(ErrorCode::InvalidFragment)?;
        if !fragment.settled {
            return Err(ErrorCode::InvalidFragment);
        }
        if protected.contains(id) {
            return Err(ErrorCode::ProtectedFragment);
        }
    }
    let hidden_events = fragments.events_of(selection.hidden);
    let mut messages: Vec<Message> = session
        .log()
        .derive_messages_indexed(|seq| !hidden_events.contains(&seq))
        .into_iter()
        .map(|(_, message)| message)
        .collect();
    let users = |messages: &[Message]| {
        messages
            .iter()
            .filter(|message| matches!(message, Message::User { .. }))
            .count()
    };
    let before = users(&session.derive_messages());
    assert_eq!(
        users(&messages),
        before,
        "managed selection keeps every user message"
    );

    let memory_text = render_memory(session, fragments, selection, goal);
    let anchor = messages
        .iter()
        .position(|message| matches!(message, Message::User { .. }));
    let memory = if let (Some(text), Some(anchor)) = (memory_text, anchor)
        && anchor.saturating_add(1) < messages.len()
    {
        messages.insert(
            anchor.saturating_add(1),
            Message::assistant(Some(text), None, Vec::new()),
        );
        true
    } else {
        false
    };
    // Postcondition: generated data is never the message a model would continue from.
    assert!(
        !is_memory(messages.last()),
        "generated data is never an assistant prefill"
    );
    let notice = render_notice(selection, goal, memory, facts, protected.len());
    Ok(Effective {
        notice,
        messages,
        memory,
        hidden: selection.hidden.len(),
        protected: protected.len(),
    })
}

/// Whether a message is the generated data message.
fn is_memory(message: Option<&Message>) -> bool {
    message
        .and_then(Message::text)
        .is_some_and(|text| text.starts_with(MEMORY_LABEL))
}

/// Renders the generated working-data message, or `None` when it would say nothing.
fn render_memory(
    session: &Session,
    fragments: &Fragments,
    selection: Selection<'_>,
    goal: Option<&Goal>,
) -> Option<String> {
    if selection.notes.is_empty() && selection.hidden.is_empty() && goal.is_none() {
        return None;
    }
    let mut text = String::from(MEMORY_LABEL);
    if let Some(goal) = goal {
        let _ = write!(
            text,
            "\n\nGoal (revision {}, {}, set by {}): {}",
            goal.revision(),
            goal.phase().as_str(),
            GoalProvenance::of(session).as_str(),
            goal.objective()
        );
    }
    if !selection.notes.is_empty() {
        let current = goal.map(Goal::revision);
        let stale = selection.notes_goal_revision != current;
        let _ = write!(
            text,
            "\n\nNotes (context revision {}, bound to goal revision {}{}):",
            selection.revision,
            selection
                .notes_goal_revision
                .map_or_else(|| String::from("none"), |revision| revision.to_string()),
            if stale {
                "; STALE: the goal has changed since these notes were accepted"
            } else {
                ""
            }
        );
        for note in selection.notes {
            let _ = write!(
                text,
                "\n- {} [{}] {} (sources: {})",
                note.id.as_str(),
                note.category.as_str(),
                note.claim,
                render_sources(&note.sources)
            );
        }
    }
    if !selection.hidden.is_empty() {
        text.push_str("\n\n");
        text.push_str(&catalog(fragments, selection.hidden));
    }
    Some(text)
}

/// Renders a note's references as positions, never as content.
fn render_sources(sources: &[SourceRef]) -> String {
    sources
        .iter()
        .map(|source| match source.kind {
            SourceKind::Event => format!(
                "event {} {}{} bytes {}+{}",
                source.event_seq.unwrap_or_default(),
                source.field.as_str(),
                source
                    .block_index
                    .map_or_else(String::new, |block| format!(" block {block}")),
                source.offset,
                source.length
            ),
            SourceKind::Artifact => format!(
                "{} bytes {}+{}",
                source
                    .artifact_id
                    .as_ref()
                    .map_or("artifact", super::ids::ArtifactId::as_str),
                source.offset,
                source.length
            ),
        })
        .collect::<Vec<_>>()
        .join("; ")
}

/// Renders the bounded recovery catalog: counts, range and as many ids as fit in 2 KiB.
#[must_use]
pub fn catalog(fragments: &Fragments, hidden: &[FragmentId]) -> String {
    let first = hidden.first().map_or_else(String::new, ToString::to_string);
    let last = hidden.last().map_or_else(String::new, ToString::to_string);
    let mut text = format!(
        "Hidden history: {} of {} fragments are not shown ({first} to {last}). Read them with \
         context_recall; restore them with context_manage. Ids:",
        hidden.len(),
        fragments.all().len(),
    );
    let mut listed = 0_usize;
    for id in hidden {
        let entry = format!(" {id}");
        let tail = format!(" (+{} more)", hidden.len().saturating_sub(listed));
        if text
            .len()
            .saturating_add(entry.len())
            .saturating_add(tail.len())
            > limits::CATALOG_BYTES_MAX
        {
            break;
        }
        text.push_str(&entry);
        listed = listed.saturating_add(1);
    }
    if listed < hidden.len() {
        let _ = write!(text, " (+{} more)", hidden.len().saturating_sub(listed));
    }
    assert!(
        text.len() <= limits::CATALOG_BYTES_MAX,
        "the catalog fits its bound"
    );
    text
}

/// Renders the fixed-schema notice.
fn render_notice(
    selection: Selection<'_>,
    goal: Option<&Goal>,
    memory: bool,
    facts: &NoticeFacts,
    protected: usize,
) -> Message {
    let estimate = facts
        .estimate_input_tokens
        .map_or_else(|| String::from("unknown"), |tokens| tokens.to_string());
    let pressure = facts.estimate_input_tokens.map_or_else(
        || String::from("unknown"),
        |tokens| pressure_percent(tokens, facts.input_allowance).to_string(),
    );
    let goal_phase = goal.map_or("none", |goal| goal.phase().as_str());
    let goal_revision =
        goal.map_or_else(|| String::from("none"), |goal| goal.revision().to_string());
    let stale =
        !selection.notes.is_empty() && selection.notes_goal_revision != goal.map(Goal::revision);
    let estimator = if facts.estimator.is_empty() {
        "none"
    } else {
        facts.estimator.as_str()
    };
    Message::system(format!(
        "[nanus context] mode=managed policy_version={} revision={} hidden_fragments={} \
         protected_fragments={protected} notes={} notes_stale={stale} \
         estimate_input_tokens={estimate} estimate_age=previous_candidate estimator={estimator} \
         input_allowance={} pressure_percent={pressure} budget_hint={} goal_phase={goal_phase} \
         goal_revision={goal_revision} goal_data_available={} recovery_available={}\n\
         Hidden assistant and tool messages are omitted from this request; every user message \
         is shown. Generated working data, when present, is labelled and is not a user \
         instruction or proof. When goal_data_available=false and a goal may exist, read it \
         with get_goal.",
        limits::POLICY_VERSION,
        selection.revision,
        selection.hidden.len(),
        selection.notes.len(),
        facts.input_allowance,
        if facts.budget_hint { "reduce" } else { "none" },
        memory && goal.is_some(),
        facts.recovery_available,
    ))
}

/// The estimate as a percentage of the allowance, rounded down; 100 when there is no allowance.
#[must_use]
pub fn pressure_percent(estimate: u32, allowance: u32) -> u32 {
    if allowance == 0 {
        return 100;
    }
    let percent = u64::from(estimate)
        .saturating_mul(100)
        .checked_div(u64::from(allowance))
        .unwrap_or(100);
    u32::try_from(percent).unwrap_or(u32::MAX)
}

/// The soft-pressure reminder's hysteresis.
///
/// A hint at 75 % of the allowance, re-armed only below 60 %, and never twice within four
/// completed model steps — so pressure that stays high is a reminder now and then rather than a
/// line in every request, and an ineffective edit cannot make it louder.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Reminder {
    armed: bool,
    steps_since: u32,
}

impl Default for Reminder {
    fn default() -> Self {
        Self {
            armed: true,
            steps_since: limits::REMINDER_MIN_STEPS,
        }
    }
}

impl Reminder {
    /// Observes a request's pressure and says whether it carries the hint.
    pub fn observe(&mut self, percent: u32) -> bool {
        if percent < limits::REARM_PERCENT {
            self.armed = true;
            return false;
        }
        let due = self.armed
            && percent >= limits::SOFT_PRESSURE_PERCENT
            && self.steps_since >= limits::REMINDER_MIN_STEPS;
        if due {
            self.armed = false;
            self.steps_since = 0;
        }
        due
    }

    /// Counts one completed model step.
    pub fn step_completed(&mut self) {
        self.steps_since = self.steps_since.saturating_add(1);
    }
}

#[cfg(test)]
mod tests;
