//! The model conversation vocabulary.
//!
//! The harness's own shape, which every adapter translates into its provider's. It
//! began as the `OpenAI` chat-completions body and still serialises that way —
//! `reasoning_content` beside `content`, a `tool_call_id` on a result — so an
//! `OpenAI`-compatible adapter can use it as written, while a provider whose wire is
//! different (Anthropic's Messages API) encodes these messages itself.
//!
//! The domain owns the shape rather than an adapter, because it carries rules the
//! whole harness must respect — for example that an assistant turn with no text
//! serialises its `content` as `""` and never as `null`, which the live `DeepSeek`
//! API rejects with a 400.
//!
//! A [`Message`] is therefore not a neutral record: it is the model-visible
//! projection of a session, and its serialisation is a contract for the adapters that
//! speak the same shape.

use core::fmt;

mod replay_context;
mod responses_replay;

pub use replay_context::ReplayContext;

use serde::de::{self, MapAccess, Visitor};
use serde::ser::SerializeMap;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use serde_json::Value;

use crate::tool::{ToolCall, ToolName};

/// Who authored a message.
///
/// The wire form is the lowercase name, which is what every `OpenAI`-compatible
/// chat endpoint expects in the `role` field.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// Instructions authored by the harness, not the user.
    System,
    /// A human turn.
    User,
    /// A model turn.
    Assistant,
    /// The result of a tool the model asked for.
    Tool,
}

impl Role {
    /// Returns the wire name of the role.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::System => "system",
            Self::User => "user",
            Self::Assistant => "assistant",
            Self::Tool => "tool",
        }
    }
}

impl fmt::Display for Role {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The provider-assigned identity of one tool call.
///
/// The value is opaque: the harness only ever matches it against the `tool_call_id`
/// of the result it produces. It is deliberately not validated, because it is
/// echo-back data from the provider rather than a name the harness derives
/// meaning from.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ToolCallId(String);

impl ToolCallId {
    /// Wraps a provider-assigned id.
    #[must_use]
    pub fn new(raw: impl Into<String>) -> Self {
        Self(raw.into())
    }

    /// Returns the id as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consumes the id, returning the underlying string.
    #[must_use]
    pub fn into_string(self) -> String {
        self.0
    }

    /// Returns `true` when the id is empty.
    ///
    /// An empty id means the provider sent a malformed stream: the harness can
    /// still match a result to it, but nothing outside the harness can.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl fmt::Display for ToolCallId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Token accounting for one model response.
///
/// The fields mirror what `DeepSeek` reports: `reasoning_tokens` is a subset of
/// `completion_tokens`, and the two cache counters partition `prompt_tokens`.
/// Totals are recomputed rather than trusted, so a provider that reports a
/// different `total_tokens` cannot make the harness's arithmetic inconsistent
/// with its own counters.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(from = "UsageWire", into = "UsageWire")]
pub struct Usage {
    /// Tokens sent to the model.
    pub prompt_tokens: u32,
    /// Tokens generated by the model, reasoning tokens included.
    pub completion_tokens: u32,
    /// The share of `completion_tokens` spent reasoning.
    pub reasoning_tokens: u32,
    /// The share of `prompt_tokens` served from the provider's prompt cache.
    pub cache_hit_tokens: u32,
    /// The share of `prompt_tokens` that missed the prompt cache.
    pub cache_miss_tokens: u32,
}

impl Usage {
    /// Builds a usage record.
    #[must_use]
    pub const fn new(
        prompt_tokens: u32,
        completion_tokens: u32,
        reasoning_tokens: u32,
        cache_hit_tokens: u32,
        cache_miss_tokens: u32,
    ) -> Self {
        Self {
            prompt_tokens,
            completion_tokens,
            reasoning_tokens,
            cache_hit_tokens,
            cache_miss_tokens,
        }
    }

    /// Returns the billable total: prompt plus completion.
    ///
    /// Saturating rather than wrapping, because a total that silently wrapped
    /// would under-report cost — the one number a budget check relies on.
    #[must_use]
    pub const fn total_tokens(&self) -> u32 {
        self.prompt_tokens.saturating_add(self.completion_tokens)
    }

    /// Adds another record's counters into this one, saturating.
    pub fn accumulate(&mut self, other: &Self) {
        self.prompt_tokens = self.prompt_tokens.saturating_add(other.prompt_tokens);
        self.completion_tokens = self
            .completion_tokens
            .saturating_add(other.completion_tokens);
        self.reasoning_tokens = self.reasoning_tokens.saturating_add(other.reasoning_tokens);
        self.cache_hit_tokens = self.cache_hit_tokens.saturating_add(other.cache_hit_tokens);
        self.cache_miss_tokens = self
            .cache_miss_tokens
            .saturating_add(other.cache_miss_tokens);
        // Postcondition: every counter is at least the value it held, and the
        // total is the sum of the two counters it is derived from.
        assert!(self.total_tokens() >= other.total_tokens());
    }
}

impl fmt::Display for Usage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} in / {} out ({} reasoning)",
            self.prompt_tokens, self.completion_tokens, self.reasoning_tokens
        )
    }
}

/// The `completion_tokens_details` object of the wire shape.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
struct CompletionTokensDetails {
    #[serde(default)]
    reasoning_tokens: u32,
}

/// The `OpenAI`-shaped usage object.
///
/// Every field is defaulted on the way in: providers omit parts of this object,
/// and a missing counter is zero rather than a parse failure.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
struct UsageWire {
    #[serde(default)]
    prompt_tokens: u32,
    #[serde(default)]
    completion_tokens: u32,
    #[serde(default)]
    total_tokens: u32,
    #[serde(default)]
    prompt_cache_hit_tokens: u32,
    #[serde(default)]
    prompt_cache_miss_tokens: u32,
    #[serde(default)]
    completion_tokens_details: CompletionTokensDetails,
}

impl From<UsageWire> for Usage {
    fn from(wire: UsageWire) -> Self {
        let usage = Self::new(
            wire.prompt_tokens,
            wire.completion_tokens,
            wire.completion_tokens_details.reasoning_tokens,
            wire.prompt_cache_hit_tokens,
            wire.prompt_cache_miss_tokens,
        );
        // The reported total is ignored in favour of the derived one; the
        // assertion records that choice so a later edit cannot silently start
        // trusting a second source of truth.
        assert!(usage.total_tokens() >= usage.completion_tokens);
        usage
    }
}

impl From<Usage> for UsageWire {
    fn from(usage: Usage) -> Self {
        Self {
            prompt_tokens: usage.prompt_tokens,
            completion_tokens: usage.completion_tokens,
            total_tokens: usage.total_tokens(),
            prompt_cache_hit_tokens: usage.cache_hit_tokens,
            prompt_cache_miss_tokens: usage.cache_miss_tokens,
            completion_tokens_details: CompletionTokensDetails {
                reasoning_tokens: usage.reasoning_tokens,
            },
        }
    }
}

/// Opaque, ordered assistant content required to replay a signed provider response.
///
/// It travels only on the named protocol and unchanged prefix. Display continues to use
/// ordinary text/reasoning, and other encoders ignore this content. No URLs are fetched.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct AssistantReplay {
    /// The protocol that produced these blocks.
    pub protocol: String,
    /// SHA-256 of that request's system, tools and preceding encoded messages.
    pub prefix_digest: String,
    /// Original/fitted request receipts. Absent for legacy Messages and decoder-only fixtures.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_receipt: Option<Box<ReplayContext>>,
    /// Original ordered provider blocks, including signed empty thinking.
    pub blocks: Vec<Value>,
}

impl AssistantReplay {
    /// Checks that replayed text and executable calls are exactly the neutral response.
    pub fn validate_response(
        &self,
        text: Option<&str>,
        calls: &[ToolCall],
    ) -> Result<(), crate::content::ContentError> {
        self.validate()?;
        if self.protocol == "openai.responses" {
            return responses_replay::response(&self.blocks, text, calls);
        }
        let original_text: String = self
            .blocks
            .iter()
            .filter(|block| block["type"] == "text")
            .filter_map(|block| block["text"].as_str())
            .collect();
        let uses: Vec<_> = self
            .blocks
            .iter()
            .filter(|block| block["type"] == "tool_use")
            .collect();
        if original_text != text.unwrap_or_default()
            || uses.len() != calls.len()
            || uses.iter().zip(calls).any(|(block, call)| {
                block["id"] != call.id.as_str()
                    || block["name"] != call.name.as_str()
                    || block["input"] != call.arguments
            })
        {
            return Err(crate::content::ContentError::new(
                "assistant replay differs from response",
            ));
        }
        Ok(())
    }

    /// Validates bounded protocol-specific replay. Images belong only in typed results.
    pub fn validate(&self) -> Result<(), crate::content::ContentError> {
        use crate::content::{ContentError, RECORD_BYTES_MAX, serialized_size};
        if !matches!(
            self.protocol.as_str(),
            "anthropic.messages" | "openai.responses"
        ) || self.prefix_digest.len() != 64
            || !self
                .prefix_digest
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit())
            || self.blocks.is_empty()
            || self.blocks.len() > 256
        {
            return Err(ContentError::new("invalid assistant replay envelope"));
        }
        serialized_size(self, RECORD_BYTES_MAX)?;
        if let Some(context) = &self.context_receipt {
            if self.protocol != "openai.responses" {
                return Err(ContentError::new(
                    "context receipt on another replay protocol",
                ));
            }
            context.validate()?;
        }
        for block in &self.blocks {
            Self::validate_item(&self.protocol, block)?;
        }
        if self.protocol == "openai.responses" {
            responses_replay::identities(&self.blocks)?;
        }
        Ok(())
    }

    /// Checks a borrowed original item before an adapter copies it into retained replay.
    /// Ciphertext is opaque; this checks shape and bounds, not cryptographic validity.
    pub fn validate_item(protocol: &str, item: &Value) -> Result<(), crate::content::ContentError> {
        crate::content::serialized_size(item, crate::content::RECORD_BYTES_MAX)?;
        match protocol {
            "anthropic.messages" => validate_replay_block(item),
            "openai.responses" => responses_replay::item(item),
            _ => Err(crate::content::ContentError::new(
                "unsupported replay protocol",
            )),
        }
    }
}

fn validate_replay_block(block: &Value) -> Result<(), crate::content::ContentError> {
    use crate::content::ContentError;
    let Some(object) = block.as_object() else {
        return Err(ContentError::new("assistant replay block is not an object"));
    };
    let fields: &[&str] = match block["type"].as_str() {
        Some("text") if block["text"].is_string() => &["type", "text"],
        Some("thinking")
            if block["thinking"].is_string()
                && block["signature"]
                    .as_str()
                    .is_some_and(|value| !value.is_empty()) =>
        {
            &["type", "thinking", "signature"]
        }
        Some("redacted_thinking")
            if block["data"]
                .as_str()
                .is_some_and(|value| !value.is_empty()) =>
        {
            &["type", "data"]
        }
        Some("tool_use")
            if block["id"].as_str().is_some_and(|id| !id.is_empty())
                && block["name"]
                    .as_str()
                    .is_some_and(|name| ToolName::new(name).is_ok())
                && block["input"].is_object() =>
        {
            &["type", "id", "name", "input"]
        }
        _ => {
            return Err(ContentError::new(
                "unsupported or malformed assistant replay block",
            ));
        }
    };
    if object.len() != fields.len() || !object.keys().all(|key| fields.contains(&key.as_str())) {
        return Err(ContentError::new("unknown assistant replay fields"));
    }
    Ok(())
}

impl<'de> Deserialize<'de> for AssistantReplay {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Wire {
            protocol: String,
            prefix_digest: String,
            #[serde(default)]
            context_receipt: Option<Box<ReplayContext>>,
            blocks: Vec<Value>,
        }
        let wire = Wire::deserialize(deserializer)?;
        let replay = Self {
            protocol: wire.protocol,
            prefix_digest: wire.prefix_digest,
            context_receipt: wire.context_receipt,
            blocks: wire.blocks,
        };
        replay.validate().map_err(de::Error::custom)?;
        Ok(replay)
    }
}

/// One entry in the conversation a model is asked to continue.
#[derive(Clone, Debug, PartialEq)]
pub enum Message {
    /// Harness-authored instructions.
    System {
        /// The instruction text.
        text: String,
    },
    /// A human turn.
    User {
        /// The turn text.
        text: String,
    },
    /// A model turn.
    Assistant {
        /// The model's visible text, absent when the turn was tool calls only.
        text: Option<String>,
        /// The model's reasoning trace, which `DeepSeek` requires back when tools
        /// are present.
        reasoning: Option<String>,
        /// Opaque provider content, when required for signed reasoning replay.
        replay: Option<AssistantReplay>,
        /// The tool calls the model asked for, in the order it asked.
        tool_calls: Vec<ToolCall>,
    },
    /// The result of one tool call.
    Tool {
        /// The call this result answers.
        call_id: ToolCallId,
        /// The rendered result the model sees.
        content: String,
        /// Ordered model content; absence means legacy text, never inferred images.
        content_blocks: Option<Vec<crate::ContentBlock>>,
        /// Whether the tool failed. Not part of the wire shape: the harness
        /// renders failures into `content` so the model can react to them.
        is_error: bool,
    },
}

impl Message {
    /// Builds a system message.
    #[must_use]
    pub fn system(text: impl Into<String>) -> Self {
        Self::System { text: text.into() }
    }

    /// Builds a user message.
    #[must_use]
    pub fn user(text: impl Into<String>) -> Self {
        Self::User { text: text.into() }
    }

    /// Builds an assistant message.
    #[must_use]
    pub fn assistant(
        text: Option<String>,
        reasoning: Option<String>,
        tool_calls: Vec<ToolCall>,
    ) -> Self {
        Self::Assistant {
            text,
            reasoning,
            tool_calls,
            replay: None,
        }
    }

    /// Builds a tool-result message.
    #[must_use]
    pub fn tool(call_id: ToolCallId, content: impl Into<String>, is_error: bool) -> Self {
        Self::Tool {
            call_id,
            content: content.into(),
            content_blocks: None,
            is_error,
        }
    }

    /// Returns the original text blocks for a tool result, or its legacy text.
    ///
    /// Image blocks are omitted here only by text encoders whose request boundary refuses
    /// images. Multimodal encoders must preserve them through their own translation.
    #[must_use]
    pub fn tool_text(&self) -> Option<String> {
        match self {
            Self::Tool {
                content_blocks: Some(blocks),
                ..
            } => Some(
                blocks
                    .iter()
                    .filter_map(|block| {
                        if let crate::ContentBlock::Text(text) = block {
                            Some(if text.ends_with('\n') {
                                text.clone()
                            } else {
                                format!("{text}\n")
                            })
                        } else {
                            None
                        }
                    })
                    .collect(),
            ),
            Self::Tool { content, .. } => Some(content.clone()),
            _ => None,
        }
    }

    /// Returns the role this message is attributed to.
    #[must_use]
    pub const fn role(&self) -> Role {
        match self {
            Self::System { .. } => Role::System,
            Self::User { .. } => Role::User,
            Self::Assistant { .. } => Role::Assistant,
            Self::Tool { .. } => Role::Tool,
        }
    }

    /// Returns the visible text, if this message has any.
    #[must_use]
    pub fn text(&self) -> Option<&str> {
        match self {
            Self::System { text } | Self::User { text } => Some(text),
            Self::Assistant { text, .. } => text.as_deref(),
            Self::Tool { content, .. } => Some(content),
        }
    }

    /// Returns the reasoning trace, if this message has one.
    #[must_use]
    pub fn reasoning(&self) -> Option<&str> {
        match self {
            Self::Assistant { reasoning, .. } => reasoning.as_deref(),
            Self::System { .. } | Self::User { .. } | Self::Tool { .. } => None,
        }
    }

    /// Returns the tool calls this message carries.
    #[must_use]
    pub fn tool_calls(&self) -> &[ToolCall] {
        match self {
            Self::Assistant { tool_calls, .. } => tool_calls,
            Self::System { .. } | Self::User { .. } | Self::Tool { .. } => &[],
        }
    }

    /// Returns `true` when this message carries nothing a model can see.
    ///
    /// Such a message is dropped by the surface fold: sending it would consume
    /// tokens and, for `DeepSeek`, risk a 400 for an empty assistant turn.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        match self {
            Self::System { text } | Self::User { text } => text.is_empty(),
            Self::Assistant {
                text,
                tool_calls,
                replay,
                ..
            } => {
                text.as_ref().is_none_or(String::is_empty)
                    && tool_calls.is_empty()
                    && replay
                        .as_ref()
                        .is_none_or(|replay| replay.protocol != "openai.responses")
            }
            Self::Tool { content, .. } => content.is_empty(),
        }
    }
}

/// The `id`/`type`/`function` envelope the wire protocol requires for a tool call.
#[derive(Serialize)]
struct ToolCallWire<'a> {
    id: &'a str,
    #[serde(rename = "type")]
    kind: &'static str,
    function: FunctionWire<'a>,
}

/// The `function` object of a tool call.
#[derive(Serialize)]
struct FunctionWire<'a> {
    name: &'a str,
    /// The arguments are a JSON *string* on the wire, not a JSON object.
    arguments: String,
}

/// A tolerant view of one wire tool call.
#[derive(Deserialize)]
struct ToolCallDe {
    #[serde(default)]
    id: String,
    #[serde(default)]
    function: Option<FunctionDe>,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    arguments: Option<Value>,
}

/// A tolerant view of the `function` object.
#[derive(Deserialize)]
struct FunctionDe {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    arguments: Option<Value>,
}

impl Serialize for ToolCall {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        ToolCallWire {
            id: self.id.as_str(),
            kind: "function",
            function: FunctionWire {
                name: self.name.as_str(),
                // `Value::to_string` is the JSON encoding; an object argument
                // therefore becomes `"{\"path\":\"...\"}"`, which is exactly
                // what the wire requires.
                arguments: self.arguments.to_string(),
            },
        }
        .serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for ToolCall {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let wire = ToolCallDe::deserialize(deserializer)?;
        let (name, arguments) = match wire.function {
            Some(function) => (
                function
                    .name
                    .or(wire.name)
                    .ok_or_else(|| de::Error::custom("a tool call has no function name"))?,
                function.arguments.or(wire.arguments),
            ),
            None => (
                wire.name
                    .ok_or_else(|| de::Error::custom("a tool call has no function name"))?,
                wire.arguments,
            ),
        };
        let name = ToolName::new(name).map_err(de::Error::custom)?;
        let arguments = decode_arguments(arguments).map_err(de::Error::custom)?;
        Ok(Self::new(ToolCallId::new(wire.id), name, arguments))
    }
}

/// Normalises the `arguments` field of a wire tool call into a JSON value.
///
/// Providers send the arguments as a JSON string; a few send them inline. `null`
/// and absence both mean "no arguments", which is an empty object rather than a
/// failure — the model is allowed to call a tool that takes nothing.
fn decode_arguments(value: Option<Value>) -> Result<Value, String> {
    match value {
        None | Some(Value::Null) => Ok(Value::Object(serde_json::Map::new())),
        Some(Value::String(raw)) => crate::tool::parse_arguments_json(&raw),
        Some(other) => Ok(other),
    }
}

impl Serialize for Message {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::System { text } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("role", Role::System.as_str())?;
                map.serialize_entry("content", text)?;
                map.end()
            }
            Self::User { text } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("role", Role::User.as_str())?;
                map.serialize_entry("content", text)?;
                map.end()
            }
            Self::Assistant {
                text,
                reasoning,
                tool_calls,
                replay,
            } => {
                let mut map = serializer.serialize_map(None)?;
                map.serialize_entry("role", Role::Assistant.as_str())?;
                // The `DeepSeek` rule this crate exists to enforce: an assistant
                // turn with no text sends `content: ""`. `null` is rejected with
                // an HTTP 400, so the empty string is not a style choice.
                map.serialize_entry("content", text.as_deref().unwrap_or(""))?;
                if let Some(reasoning) = reasoning.as_deref() {
                    // Reasoning must come back on the next request when tools are
                    // present, so it round-trips rather than being dropped.
                    map.serialize_entry("reasoning_content", reasoning)?;
                }
                if !tool_calls.is_empty() {
                    map.serialize_entry("tool_calls", tool_calls)?;
                }
                if let Some(replay) = replay {
                    replay
                        .validate_response(text.as_deref(), tool_calls)
                        .map_err(serde::ser::Error::custom)?;
                    map.serialize_entry("assistant_replay", replay)?;
                }
                map.end()
            }
            Self::Tool {
                call_id,
                content,
                content_blocks,
                is_error,
            } => {
                let mut map = serializer.serialize_map(Some(3))?;
                map.serialize_entry("role", Role::Tool.as_str())?;
                map.serialize_entry("tool_call_id", call_id.as_str())?;
                map.serialize_entry("content", content)?;
                if let Some(blocks) = content_blocks {
                    crate::content::validate_blocks(blocks).map_err(serde::ser::Error::custom)?;
                    map.serialize_entry("content_blocks", blocks)?;
                    map.serialize_entry("is_error", is_error)?;
                }
                map.end()
            }
        }
    }
}

/// The field state accumulated while visiting one message object.
#[derive(Default)]
struct MessageFields {
    role: Option<String>,
    content: Option<Value>,
    tool_calls: Vec<ToolCall>,
    reasoning: Option<String>,
    call_id: Option<String>,
    is_error: bool,
    content_blocks: Option<Vec<crate::ContentBlock>>,
    replay: Option<AssistantReplay>,
}

impl MessageFields {
    /// Builds a message from the collected fields.
    fn finish(self) -> Result<Message, String> {
        let role = self
            .role
            .ok_or_else(|| String::from("a message has no role"))?;
        let text = text_of(self.content)?;
        match role.as_str() {
            "system" => Ok(Message::system(text.unwrap_or_default())),
            "user" => Ok(Message::user(text.unwrap_or_default())),
            "assistant" => {
                if let Some(replay) = &self.replay {
                    replay
                        .validate_response(text.as_deref(), &self.tool_calls)
                        .map_err(|error| error.to_string())?;
                }
                // An empty string and an absent field both mean "no text"; they
                // are normalised so the surface fold has one case to handle.
                let text = text.filter(|value| !value.is_empty());
                Ok(Message::Assistant {
                    text,
                    reasoning: self.reasoning,
                    tool_calls: self.tool_calls,
                    replay: self.replay,
                })
            }
            "tool" => {
                let call_id = self
                    .call_id
                    .ok_or_else(|| String::from("a tool message has no tool_call_id"))?;
                if let Some(blocks) = &self.content_blocks {
                    crate::content::validate_blocks(blocks).map_err(|error| error.to_string())?;
                }
                Ok(Message::Tool {
                    call_id: ToolCallId::new(call_id),
                    content: text.unwrap_or_default(),
                    is_error: self.is_error,
                    content_blocks: self.content_blocks,
                })
            }
            other => Err(format!("unknown message role {other:?}")),
        }
    }
}

/// Projects a wire `content` field onto text.
///
/// A string is taken as-is, `null` means absent, and an array of content parts
/// is flattened by concatenating its `text` parts so a multimodal user turn
/// degrades to its readable half instead of failing.
fn text_of(value: Option<Value>) -> Result<Option<String>, String> {
    match value {
        None | Some(Value::Null) => Ok(None),
        Some(Value::String(text)) => Ok(Some(text)),
        Some(Value::Array(parts)) => {
            let mut out = String::new();
            for part in parts {
                match part {
                    Value::Object(map) => {
                        if let Some(Value::String(text)) = map.get("text") {
                            out.push_str(text);
                        }
                    }
                    Value::String(text) => out.push_str(&text),
                    other => {
                        return Err(format!("unsupported content part {other}"));
                    }
                }
            }
            Ok(Some(out))
        }
        Some(other) => Err(format!("unsupported content {other}")),
    }
}

/// Deserialises a [`Message`] from the `OpenAI` wire shape.
struct MessageVisitor;

impl<'de> Visitor<'de> for MessageVisitor {
    type Value = Message;

    fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("a chat message object with a role")
    }

    fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<Self::Value, A::Error> {
        let mut fields = MessageFields::default();
        while let Some(key) = map.next_key::<String>()? {
            match key.as_str() {
                "role" => fields.role = Some(map.next_value()?),
                "content" => fields.content = Some(map.next_value()?),
                "tool_calls" => fields.tool_calls = map.next_value()?,
                "reasoning_content" | "reasoning" => fields.reasoning = map.next_value()?,
                "tool_call_id" => fields.call_id = map.next_value()?,
                "is_error" => fields.is_error = map.next_value()?,
                "content_blocks" => fields.content_blocks = map.next_value()?,
                "assistant_replay" => fields.replay = map.next_value()?,
                _ => {
                    map.next_value::<de::IgnoredAny>()?;
                }
            }
        }
        // Unknown keys are ignored so a provider may add fields without breaking
        // the harness; the fields this visitor does understand are the six
        // matched above.
        fields.finish().map_err(de::Error::custom)
    }
}

impl<'de> Deserialize<'de> for Message {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        deserializer.deserialize_map(MessageVisitor)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tool::ToolName;

    fn tool_name(raw: &str) -> ToolName {
        ToolName::new(raw).unwrap_or_else(|error| panic!("test tool name {raw}: {error}"))
    }

    fn read_tool() -> ToolCall {
        ToolCall::new(
            ToolCallId::new("call-1"),
            tool_name("read"),
            serde_json::json!({ "path": "src/lib.rs" }),
        )
    }

    #[test]
    fn an_assistant_turn_without_text_sends_an_empty_string() {
        // The DeepSeek rule: `content` is `""`, never `null`. A `null` here is an
        // HTTP 400 from the live API, so this assertion is the contract.
        let message = Message::assistant(None, None, vec![read_tool()]);
        let wire = serde_json::to_value(&message).unwrap_or(Value::Null);
        assert_eq!(
            wire.get("role"),
            Some(&Value::String("assistant".to_owned()))
        );
        assert_eq!(wire.get("content"), Some(&Value::String(String::new())));
        assert_ne!(wire.get("content"), Some(&Value::Null));
        assert!(wire.get("content").is_some(), "content is always present");
    }

    #[test]
    fn an_assistant_turn_without_text_or_tools_still_sends_content() {
        let message = Message::assistant(None, None, Vec::new());
        let wire = serde_json::to_value(&message).unwrap_or(Value::Null);
        assert_eq!(wire.get("content"), Some(&Value::String(String::new())));
        assert!(
            wire.get("tool_calls").is_none(),
            "empty tool calls are omitted"
        );
        assert!(
            message.is_empty(),
            "an empty assistant turn is dropped by the fold"
        );
    }

    #[test]
    fn tool_calls_serialise_in_the_function_envelope() {
        let wire = serde_json::to_value(read_tool()).unwrap_or(Value::Null);
        assert_eq!(
            wire.get("type"),
            Some(&Value::String("function".to_owned()))
        );
        assert_eq!(wire.get("id"), Some(&Value::String("call-1".to_owned())));
        let function = wire.get("function");
        assert!(function.is_some(), "the function envelope is required");
        let Some(function) = function else { return };
        assert_eq!(
            function.get("name"),
            Some(&Value::String("read".to_owned()))
        );
        // Arguments travel as a JSON *string*, not as a nested object.
        let arguments = function.get("arguments");
        assert!(matches!(arguments, Some(Value::String(_))));
    }

    #[test]
    fn tool_calls_round_trip_through_the_wire() {
        let original = read_tool();
        let wire = serde_json::to_string(&original).unwrap_or_default();
        let parsed: Result<ToolCall, _> = serde_json::from_str(&wire);
        assert!(parsed.is_ok(), "the wire shape round-trips: {wire}");
        assert_eq!(parsed.ok(), Some(original));
    }

    #[test]
    fn a_tool_result_uses_the_tool_role_and_call_id() {
        let message = Message::tool(ToolCallId::new("call-9"), "42", false);
        let wire = serde_json::to_value(&message).unwrap_or(Value::Null);
        assert_eq!(wire.get("role"), Some(&Value::String("tool".to_owned())));
        assert_eq!(
            wire.get("tool_call_id"),
            Some(&Value::String("call-9".to_owned()))
        );
        assert_eq!(wire.get("content"), Some(&Value::String("42".to_owned())));
        // `is_error` is harness state, not wire state.
        assert!(wire.get("is_error").is_none());
    }

    #[test]
    fn reasoning_content_round_trips() {
        let message = Message::assistant(
            Some("answer".to_owned()),
            Some("because".to_owned()),
            vec![read_tool()],
        );
        let wire = serde_json::to_string(&message).unwrap_or_default();
        let parsed: Result<Message, _> = serde_json::from_str(&wire);
        assert!(parsed.is_ok(), "reasoning survives the round trip: {wire}");
        let Ok(parsed) = parsed else { return };
        assert_eq!(parsed.reasoning(), Some("because"));
        assert_eq!(parsed.text(), Some("answer"));
        assert_eq!(parsed.tool_calls().len(), 1);
    }

    #[test]
    fn an_absent_content_field_is_not_an_error() {
        // A provider that omits `content` for a tool-call turn must not break the
        // parse; the turn simply has no text.
        let raw = r#"{"role":"assistant","tool_calls":[{"id":"c","type":"function",
            "function":{"name":"read","arguments":"{\"path\":\"a\"}"}}]}"#;
        let parsed: Result<Message, _> = serde_json::from_str(raw);
        assert!(parsed.is_ok(), "a missing content field parses: {raw}");
        let Ok(parsed) = parsed else { return };
        assert_eq!(parsed.text(), None);
        assert_eq!(parsed.tool_calls().len(), 1);
    }

    #[test]
    fn an_empty_string_content_normalises_to_no_text() {
        let raw = r#"{"role":"assistant","content":"","tool_calls":[]}"#;
        let parsed: Result<Message, _> = serde_json::from_str(raw);
        assert!(parsed.is_ok());
        let Ok(parsed) = parsed else { return };
        assert_eq!(parsed.text(), None, "empty text is absence, not emptiness");
        assert!(parsed.is_empty());
    }

    #[test]
    fn an_array_content_is_flattened_to_its_text_parts() {
        let raw =
            r#"{"role":"user","content":[{"type":"text","text":"a"},{"type":"text","text":"b"}]}"#;
        let parsed: Result<Message, _> = serde_json::from_str(raw);
        assert!(parsed.is_ok());
        let Ok(parsed) = parsed else { return };
        assert_eq!(parsed.text(), Some("ab"));
    }

    #[test]
    fn an_unknown_role_is_a_typed_parse_error() {
        let raw = r#"{"role":"wizard","content":"hi"}"#;
        let parsed: Result<Message, _> = serde_json::from_str(raw);
        assert!(parsed.is_err(), "an unknown role is rejected, not guessed");
    }

    #[test]
    fn a_tool_message_without_a_call_id_is_rejected() {
        let raw = r#"{"role":"tool","content":"hi"}"#;
        let parsed: Result<Message, _> = serde_json::from_str(raw);
        assert!(
            parsed.is_err(),
            "a tool result that cannot be matched to a call is not a message"
        );
    }

    #[test]
    fn malformed_tool_arguments_are_a_parse_error() {
        // The model really does send malformed JSON. At this boundary it is a
        // parse failure; the adapter reports it as a malformed stream rather
        // than letting a half-parsed call reach a tool.
        let raw = r#"{"role":"assistant","content":"x","tool_calls":[{"id":"c","type":"function",
            "function":{"name":"read","arguments":"{\"path\":"}}]}"#;
        let parsed: Result<Message, _> = serde_json::from_str(raw);
        assert!(parsed.is_err(), "truncated arguments are rejected");
    }

    #[test]
    fn usage_is_recomputed_from_its_parts() {
        let raw = r#"{"prompt_tokens":10,"completion_tokens":5,"total_tokens":9999,
            "prompt_cache_hit_tokens":4,"prompt_cache_miss_tokens":6,
            "completion_tokens_details":{"reasoning_tokens":3}}"#;
        let parsed: Result<Usage, _> = serde_json::from_str(raw);
        assert!(parsed.is_ok());
        let Ok(usage) = parsed else { return };
        assert_eq!(usage.total_tokens(), 15, "the derived total wins");
        assert_eq!(usage.reasoning_tokens, 3);
        assert_eq!(
            usage
                .cache_hit_tokens
                .saturating_add(usage.cache_miss_tokens),
            10
        );
    }

    #[test]
    fn usage_serialises_the_reported_total() {
        let usage = Usage::new(10, 5, 1, 0, 10);
        let wire = serde_json::to_value(usage).unwrap_or(Value::Null);
        assert_eq!(wire.get("total_tokens"), Some(&serde_json::json!(15)));
        assert_eq!(
            wire.get("prompt_cache_miss_tokens"),
            Some(&serde_json::json!(10))
        );
    }

    #[test]
    fn usage_accumulates_without_wrapping() {
        let mut total = Usage::new(1, 2, 0, 0, 1);
        total.accumulate(&Usage::new(3, 4, 1, 1, 2));
        assert_eq!(total.total_tokens(), 10);
        assert_eq!(total.reasoning_tokens, 1);
        // Saturation, not wrap-around: a budget check must not go negative.
        let mut near_max = Usage::new(u32::MAX, u32::MAX, 0, 0, 0);
        near_max.accumulate(&Usage::new(1, 1, 0, 0, 0));
        assert_eq!(near_max.prompt_tokens, u32::MAX);
    }

    #[test]
    fn roles_carry_their_wire_names() {
        assert_eq!(Role::System.as_str(), "system");
        assert_eq!(Role::User.as_str(), "user");
        assert_eq!(Role::Assistant.as_str(), "assistant");
        assert_eq!(Role::Tool.as_str(), "tool");
        assert_eq!(Role::Assistant.to_string(), "assistant");
    }
}
